import './app-v4.js';
import { attachEcologyRuntime } from './bootstrap/attachEcologyRuntime.js';
import { attachRoadRuntime } from './bootstrap/attachRoadRuntime.js';
import { attachSeasonRuntime } from './bootstrap/attachSeasonRuntime.js';
import { attachFarmRuntime } from './bootstrap/attachFarmRuntime.js';
import { attachFarmExpansionRuntime } from './bootstrap/attachFarmExpansionRuntime.js';
import { attachFoodStorageRuntime } from './bootstrap/attachFoodStorageRuntime.js';
import { attachStockTargetRuntime } from './bootstrap/attachStockTargetRuntime.js';
import { attachToolRuntime } from './bootstrap/attachToolRuntime.js';
import { attachLaborCostRuntime } from './bootstrap/attachLaborCostRuntime.js';
import { attachWorldSpeedRuntime } from './bootstrap/attachWorldSpeedRuntime.js';
import { attachWorldSaveRuntime } from './bootstrap/attachWorldSaveRuntime.js';
import { attachMapHudRuntime } from './bootstrap/attachMapHudRuntime.js';
import { attachObserverUiRuntime } from './bootstrap/attachObserverUiRuntime.js';
import { attachBuildInfoRuntime } from './bootstrap/attachBuildInfoRuntime.js';

attachEcologyRuntime();
attachRoadRuntime();
attachSeasonRuntime();
attachFarmRuntime();
attachFarmExpansionRuntime();
attachFoodStorageRuntime();
attachStockTargetRuntime();
attachToolRuntime();
attachLaborCostRuntime();
attachWorldSpeedRuntime();
attachWorldSaveRuntime();
attachMapHudRuntime();
attachObserverUiRuntime();
attachBuildInfoRuntime();
